In [2]:
# Importing necessary library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
books = pd.read_csv("bookrecomdataset/Books.csv", encoding='latin-1')
books.head()

C:\Users\BHAUMIK\AppData\Local\Temp\ipykernel_6708\3801998742.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv("bookrecomdataset/Books.csv", encoding='latin-1')

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [4]:
books = books[['ISBN','Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher','Image-URL-L']]
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...

In [5]:
# Lets remane some wierd columns name
books.rename(columns={"Book-Title":'title',
                      'Book-Author':'author',
                     "Year-Of-Publication":'year',
                     "Publisher":"publisher",
                     "Image-URL-L":"image_url"},inplace=True)
books.head()

,ISBN,title,author,year,publisher,image_url
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...

In [6]:
print(books.shape)

(271360, 6)

In [7]:
ratings  = pd.read_csv("bookrecomdataset\Ratings.csv", encoding='latin-1')
ratings .head()

<>:1: SyntaxWarning: invalid escape sequence '\R'
<>:1: SyntaxWarning: invalid escape sequence '\R'
C:\Users\BHAUMIK\AppData\Local\Temp\ipykernel_6708\1363589714.py:1: SyntaxWarning: invalid escape sequence '\R'
  ratings  = pd.read_csv("bookrecomdataset\Ratings.csv", encoding='latin-1')

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [8]:
# Lets remane some wierd columns name
ratings.rename(columns={"User-ID":'user_id',
                      'Book-Rating':'rating'},inplace=True)
ratings.head()

   user_id        ISBN  rating
0   276725  034545104X       0
1   276726  0155061224       5
2   276727  0446520802       0
3   276729  052165615X       3
4   276729  0521795028       6

In [9]:
ratings.shape

(1149780, 3)

In [10]:
users  = pd.read_csv("bookrecomdataset/Users.csv", encoding='latin-1')
users .head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [11]:
# Lets remane some wierd columns name
users.rename(columns={"User-ID":'user_id',
                      'Location':'location',
                     "Age":'age'},inplace=True)
users.head()

   user_id                            location   age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

Now we have 3 dataframes

books

users

ratings

In [12]:
ratings['user_id'].value_counts()

user_id
11676     13602
198711     7550
153662     6109
98391      5891
35859      5850
          ...
119573        1
276706        1
276697        1
276679        1
276676        1
Name: count, Length: 105283, dtype: int64

In [13]:
ratings['user_id'].unique().shape

(105283,)

In [14]:
x = ratings['user_id'].value_counts() > 200

In [15]:
x[x].shape

(899,)

In [16]:
y = x[x].index

In [17]:
y

Index([ 11676, 198711, 153662,  98391,  35859, 212898, 278418,  76352, 110973,
       235105,
       ...
       116122,  44296,  28634,  59727,  73681, 274808, 188951,   9856, 155916,
       268622],
      dtype='int64', name='user_id', length=899)

In [18]:
ratings = ratings[ratings['user_id'].isin(y)]

In [19]:
ratings.head()

      user_id        ISBN  rating
1456   277427  002542730X      10
1457   277427  0026217457       0
1458   277427  003008685X       8
1459   277427  0030615321       0
1460   277427  0060002050       0

In [20]:
ratings.shape

(526356, 3)

In [21]:
books.head()

,ISBN,title,author,year,publisher,image_url
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...

In [22]:
ratings_with_books = ratings.merge(books,on='ISBN')

In [23]:
ratings_with_books.head()

,user_id,ISBN,rating,title,author,year,publisher,image_url
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...
1,277427,0026217457,0,Vegetarian Times Complete Cookbook,Lucy Moll,1995,John Wiley &amp; Sons,http://images.amazon.com/images/P/0026217457.0...
2,277427,003008685X,8,Pioneers,James Fenimore Cooper,1974,Thomson Learning,http://images.amazon.com/images/P/003008685X.0...
3,277427,0030615321,0,"Ask for May, Settle for June (A Doonesbury book)",G. B. Trudeau,1982,Henry Holt &amp; Co,http://images.amazon.com/images/P/0030615321.0...
4,277427,0060002050,0,On a Wicked Dawn (Cynster Novels),Stephanie Laurens,2002,Avon Books,http://images.amazon.com/images/P/0060002050.0...

In [24]:
ratings_with_books.shape

(487671, 8)

In [25]:
number_rating = ratings_with_books.groupby('title')['rating'].count().reset_index()
number_rating.head()

                                               title  rating
0   A Light in the Storm: The Civil War Diary of ...       2
1                              Always Have Popsicles       1
2               Apple Magic (The Collector's series)       1
3   Beyond IBM: Leadership Marketing and Finance ...       1
4   Clifford Visita El Hospital (Clifford El Gran...       1

In [26]:
number_rating.rename(columns={
    'rating': 'num of rating',
},inplace=True)

In [27]:
number_rating.head()

                                               title  num of rating
0   A Light in the Storm: The Civil War Diary of ...              2
1                              Always Have Popsicles              1
2               Apple Magic (The Collector's series)              1
3   Beyond IBM: Leadership Marketing and Finance ...              1
4   Clifford Visita El Hospital (Clifford El Gran...              1

In [28]:
Avg_ratings_with_books = ratings_with_books.groupby('title')['rating'].mean().reset_index()

In [29]:
Avg_ratings_with_books.head()

                                               title  rating
0   A Light in the Storm: The Civil War Diary of ...     4.5
1                              Always Have Popsicles     0.0
2               Apple Magic (The Collector's series)     0.0
3   Beyond IBM: Leadership Marketing and Finance ...     0.0
4   Clifford Visita El Hospital (Clifford El Gran...     0.0

In [30]:
final_rating = Avg_ratings_with_books.merge(number_rating,on='title')

In [31]:
final_rating.head()

                                               title  rating  num of rating
0   A Light in the Storm: The Civil War Diary of ...     4.5              2
1                              Always Have Popsicles     0.0              1
2               Apple Magic (The Collector's series)     0.0              1
3   Beyond IBM: Leadership Marketing and Finance ...     0.0              1
4   Clifford Visita El Hospital (Clifford El Gran...     0.0              1

In [32]:
final_rating.shape

(160269, 3)

In [33]:
popular_books = final_rating[final_rating['num of rating'] >= 100].sort_values('num of rating',ascending=False)

In [34]:
popular_books.shape

(158, 3)

In [35]:
popular_books.head()

                            title    rating  num of rating
156313                Wild Animus  0.438017            363
19140       Bridget Jones's Diary  2.664260            277
130224  The Lovely Bones: A Novel  3.203704            270
132891               The Notebook  2.070539            241
133898          The Pelican Brief  1.978814            236

In [36]:
popular_books.merge(books,on='title').drop_duplicates('title')

,title,rating,num of rating,ISBN,author,year,publisher,image_url
0,Wild Animus,0.438017,363,0971880107,Rich Shapero,2004,Too Far,http://images.amazon.com/images/P/0971880107.0...
1,Bridget Jones's Diary,2.664260,277,0330332775,Helen Fielding,1997,Picador (UK),http://images.amazon.com/images/P/0330332775.0...
7,The Lovely Bones: A Novel,3.203704,270,0316666343,Alice Sebold,2002,"Little, Brown",http://images.amazon.com/images/P/0316666343.0...
8,The Notebook,2.070539,241,0446605239,Nicholas Sparks,1998,Warner Books,http://images.amazon.com/images/P/0446605239.0...
13,The Pelican Brief,1.978814,236,0440214041,John Grisham,1993,Dell,http://images.amazon.com/images/P/0440214041.0...
...,...,...,...,...,...,...,...,...
651,The Lost World,1.346535,101,034540288X,Michael Crichton,1996,Ballantine Books,http://images.amazon.com/images/P/034540288X.0...
658,The Rescue,1.801980,101,0446610399,Nicholas Sparks,2001,Warner Books,http://images.amazon.com/images/P/0446610399.0...
663,The Hunt for Red October,1.118812,101,0425120279,Tom Clancy,1990,Berkley Publishing Group,http://images.amazon.com/images/P/0425120279.0...
666,Dance upon the Air (Three Sisters Island Trilogy),1.930000,100,0515131229,Nora Roberts,2003,Jove Books,http://images.amazon.com/images/P/0515131229.0...
667,The Catcher in the Rye,2.980000,100,0316769487,J.D. Salinger,1991,"Little, Brown",http://images.amazon.com/images/P/0316769487.0...

In [37]:
popular_books.shape

(158, 3)

# collaborative

In [38]:
ratings_with_books.head()

,user_id,ISBN,rating,title,author,year,publisher,image_url
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...
1,277427,0026217457,0,Vegetarian Times Complete Cookbook,Lucy Moll,1995,John Wiley &amp; Sons,http://images.amazon.com/images/P/0026217457.0...
2,277427,003008685X,8,Pioneers,James Fenimore Cooper,1974,Thomson Learning,http://images.amazon.com/images/P/003008685X.0...
3,277427,0030615321,0,"Ask for May, Settle for June (A Doonesbury book)",G. B. Trudeau,1982,Henry Holt &amp; Co,http://images.amazon.com/images/P/0030615321.0...
4,277427,0060002050,0,On a Wicked Dawn (Cynster Novels),Stephanie Laurens,2002,Avon Books,http://images.amazon.com/images/P/0060002050.0...

In [39]:
ratings_with_books.shape

(487671, 8)

select only those user that have >200 rating books

In [52]:
x = ratings_with_books.groupby('user_id').count()['rating'] > 200

In [57]:
active_user = x[x].index

In [73]:
filter_rating_user = ratings_with_books[ratings_with_books['user_id'].isin(active_user)]

In [74]:
filter_rating_user.head()

,user_id,ISBN,rating,title,author,year,publisher,image_url
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...
1,277427,0026217457,0,Vegetarian Times Complete Cookbook,Lucy Moll,1995,John Wiley &amp; Sons,http://images.amazon.com/images/P/0026217457.0...
2,277427,003008685X,8,Pioneers,James Fenimore Cooper,1974,Thomson Learning,http://images.amazon.com/images/P/003008685X.0...
3,277427,0030615321,0,"Ask for May, Settle for June (A Doonesbury book)",G. B. Trudeau,1982,Henry Holt &amp; Co,http://images.amazon.com/images/P/0030615321.0...
4,277427,0060002050,0,On a Wicked Dawn (Cynster Novels),Stephanie Laurens,2002,Avon Books,http://images.amazon.com/images/P/0060002050.0...

In [114]:
y = filter_rating_user.groupby('title').count()['rating']>=50

In [115]:
famous_books = y[y].index

In [116]:
famous_books

Index(['1984', '1st to Die: A Novel', '2nd Chance', '4 Blondes',
       'A Bend in the Road', 'A Case of Need',
       'A Child Called \It\": One Child's Courage to Survive"',
       'A Civil Action', 'A Day Late and a Dollar Short', 'A Fine Balance',
       ...
       'Winter Solstice', 'Wish You Well', 'Without Remorse',
       'Wizard and Glass (The Dark Tower, Book 4)', 'Wuthering Heights',
       'Year of Wonders', 'You Belong To Me',
       'Zen and the Art of Motorcycle Maintenance: An Inquiry into Values',
       'Zoya', '\O\" Is for Outlaw"'],
      dtype='object', name='title', length=706)

In [121]:
finaaal_ratings = filter_rating_user[filter_rating_user['title'].isin(famous_books)]

In [122]:
finaaal_ratings.shape

(58586, 8)

In [125]:
finaaal_ratings.head()

,user_id,ISBN,rating,title,author,year,publisher,image_url
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...
13,277427,0060930535,0,The Poisonwood Bible: A Novel,Barbara Kingsolver,1999,Perennial,http://images.amazon.com/images/P/0060930535.0...
15,277427,0060934417,0,Bel Canto: A Novel,Ann Patchett,2002,Perennial,http://images.amazon.com/images/P/0060934417.0...
18,277427,0061009059,9,One for the Money (Stephanie Plum Novels (Pape...,Janet Evanovich,1995,HarperTorch,http://images.amazon.com/images/P/0061009059.0...
24,277427,006440188X,0,The Secret Garden,Frances Hodgson Burnett,1998,HarperTrophy,http://images.amazon.com/images/P/006440188X.0...

In [131]:
pt = finaaal_ratings.pivot_table(index='title',columns='user_id',values='rating')

In [134]:
pt.fillna(0,inplace=True)

In [135]:
pt

user_id,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Bend in the Road,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0

In [141]:
!pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.7.1-cp312-cp312-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.22.0 in c:\users\bhaumik\documents\skyttus\machine learning\.venv\lib\site-packages (from scikit-learn) (2.3.2)
Collecting scipy>=1.8.0 (from scikit-learn)
  Downloading scipy-1.16.1-cp312-cp312-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.2.0 (from scikit-learn)
  Downloading joblib-1.5.1-py3-none-any.whl.metadata (5.6 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.7.1-cp312-cp312-win_amd64.whl (8.7 MB)
   ---------------------------------------- 0.0/8.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.7 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.7 MB 882.6 kB/s eta 0:00:10
   -- ------------------------------------- 0.5/8.7 MB 882.6 kB/s eta 0:00:10
   --- ------------------------------------ 0.8/8.7 MB 838.9 kB/s eta 0:00:10
   ---- ----------------------------------- 1.0/8.7 MB 839.3 kB/s eta 0:00:10
   ---- ----------------------------------- 1.0/8.7 MB 839.3 kB/s eta 0:00:10
   ------ --------------------------------- 1.3/8.7 MB 721.7 kB/s eta 0:00:11
   ------ --------------------------------- 1.3/8.7 MB 721.7 kB/s eta 0:00:11
   ------ --------------------------------- 1.3/8.7 MB 721.7 kB/s eta 0:00:11
   ------ --------------------------------- 1.3/8.7 MB 721.7 kB/s eta 0:00:11
   ------ --------------------------------- 1.3/8.7 MB 721.7 kB/s eta 0:00:11
   ------ --------------------------------- 1.3/8.7 MB 721.7 kB/s eta 0:00:11
   ------ --------------------------------- 1.3/8.7 MB 721.7 kB/s eta 0:00:11
   ------ --------------------------------- 1.3/8.7 MB 721.7 kB/s eta 0:00:11
   ------ --------------------------------- 1.3/8.7 MB 721.7 kB/s eta 0:00:11
   ------ --------------------------------- 1.3/8.7 MB 721.7 kB/s eta 0:00:11
   ------- -------------------------------- 1.6/8.7 MB 386.6 kB/s eta 0:00:19
   -------- ------------------------------- 1.8/8.7 MB 433.9 kB/s eta 0:00:16
   -------- ------------------------------- 1.8/8.7 MB 433.9 kB/s eta 0:00:16
   -------- ------------------------------- 1.8/8.7 MB 433.9 kB/s eta 0:00:16
   -------- ------------------------------- 1.8/8.7 MB 433.9 kB/s eta 0:00:16
   -------- ------------------------------- 1.8/8.7 MB 433.9 kB/s eta 0:00:16
   -------- ------------------------------- 1.8/8.7 MB 433.9 kB/s eta 0:00:16
   -------- ------------------------------- 1.8/8.7 MB 433.9 kB/s eta 0:00:16
   -------- ------------------------------- 1.8/8.7 MB 433.9 kB/s eta 0:00:16
   -------- ------------------------------- 1.8/8.7 MB 433.9 kB/s eta 0:00:16
   -------- ------------------------------- 1.8/8.7 MB 433.9 kB/s eta 0:00:16
   -------- ------------------------------- 1.8/8.7 MB 433.9 kB/s eta 0:00:16
   -------- ------------------------------- 1.8/8.7 MB 433.9 kB/s eta 0:00:16
   -------- ------------------------------- 1.8/8.7 MB 433.9 kB/s eta 0:00:16
   -------- ------------------------------- 1.8/8.7 MB 433.9 kB/s eta 0:00:16
   -------- ------------------------------- 1.8/8.7 MB 433.9 kB/s eta 0:00:16
   -------- ------------------------------- 1.8/8.7 MB 433.9 kB/s eta 0:00:16
   -------- ------------------------------- 1.8/8.7 MB 433.9 kB/s eta 0:00:16
   --------- ------------------------------ 2.1/8.7 MB 247.2 kB/s eta 0:00:27
   ---------- ----------------------------- 2.4/8.7 MB 275.0 kB/s eta 0:00:24
   ------------ --------------------------- 2.6/8.7 MB 302.6 kB/s eta 0:00:21
   ------------- -------------------------- 2.9/8.7 MB 330.9 kB/s eta 0:00:18
   -------------- ------------------------- 3.1/8.7 MB 354.9 kB/s eta 0:00:16
   --------------- ------------------------ 3.4/8.7 MB 379.1 kB/s eta 0:00:15
   ------------------ --------------------- 3.9/8.7 MB 421.7 kB/s eta 0:00:12
   ------------------- -------------------- 4.2/8.7 MB 444.7 kB/s eta 0:00:11
   -------------------- ------------------- 4.5/8.7 MB 463.6 kB/s eta 0:00:10
   --------------------- ------------------ 4.7/8.7 MB 483.4 kB/s eta 0:00:09
   ------------------------ --------------- 5.2/8.7 MB 521.7 kB/s eta 0:00:07
   ------------------------- -------------- 5.5/8.7 MB 543.0 kB/s eta 0:00:06
   --------------------------- ------------ 6.0/8.7 MB 578.6 kB/s eta 0:00:05
   ------------------------------ --------- 6.6/8.7 MB 615.7 kB/s eta 0:00:04
   ------------------------------- -------- 6.8/8.7 MB 632.6 kB/s eta 0:00:04
   -------------------------------- ------- 7.1/8.7 MB 645.3 kB/s eta 0:00:03
   --------------------------------- ------ 7.3/8.7 MB 652.8 kB/s eta 0:00:03
   --------------------------------- ------ 7.3/8.7 MB 652.8 kB/s eta 0:00:03
   ---------------------------------- ----- 7.6/8.7 MB 654.3 kB/s eta 0:00:02
   ---------------------------------- ----- 7.6/8.7 MB 654.3 kB/s eta 0:00:02
   ------------------------------------- -- 8.1/8.7 MB 670.2 kB/s eta 0:00:01
   ------------------------------------- -- 8.1/8.7 MB 670.2 kB/s eta 0:00:01
   -------------------------------------- - 8.4/8.7 MB 679.9 kB/s eta 0:00:01
   ---------------------------------------  8.7/8.7 MB 682.2 kB/s eta 0:00:01
   ---------------------------------------- 8.7/8.7 MB 672.9 kB/s eta 0:00:00
Downloading joblib-1.5.1-py3-none-any.whl (307 kB)
Downloading scipy-1.16.1-cp312-cp312-win_amd64.whl (38.5 MB)
   ---------------------------------------- 0.0/38.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/38.5 MB ? eta -:--:--
    --------------------------------------- 0.5/38.5 MB 2.1 MB/s eta 0:00:19
    --------------------------------------- 0.8/38.5 MB 1.7 MB/s eta 0:00:23
   - -------------------------------------- 1.0/38.5 MB 1.7 MB/s eta 0:00:23
   - -------------------------------------- 1.0/38.5 MB 1.7 MB/s eta 0:00:23
   - -------------------------------------- 1.0/38.5 MB 1.7 MB/s eta 0:00:23
   - -------------------------------------- 1.0/38.5 MB 1.7 MB/s eta 0:00:23
   - -------------------------------------- 1.0/38.5 MB 1.7 MB/s eta 0:00:23
   - -------------------------------------- 1.0/38.5 MB 1.7 MB/s eta 0:00:23
   - -------------------------------------- 1.6/38.5 MB 693.5 kB/s eta 0:00:54
   - -------------------------------------- 1.8/38.5 MB 780.6 kB/s eta 0:00:47
   -- ------------------------------------- 2.1/38.5 MB 827.0 kB/s eta 0:00:45
   -- ------------------------------------- 2.4/38.5 MB 844.3 kB/s eta 0:00:43
   -- ------------------------------------- 2.6/38.5 MB 867.7 kB/s eta 0:00:42
   -- ------------------------------------- 2.9/38.5 MB 907.1 kB/s eta 0:00:40
   --- ------------------------------------ 3.1/38.5 MB 951.4 kB/s eta 0:00:38
   --- ------------------------------------ 3.1/38.5 MB 951.4 kB/s eta 0:00:38
   --- ------------------------------------ 3.1/38.5 MB 951.4 kB/s eta 0:00:38
   --- ------------------------------------ 3.1/38.5 MB 951.4 kB/s eta 0:00:38
   --- ------------------------------------ 3.1/38.5 MB 951.4 kB/s eta 0:00:38
   --- ------------------------------------ 3.1/38.5 MB 951.4 kB/s eta 0:00:38
   --- ------------------------------------ 3.1/38.5 MB 951.4 kB/s eta 0:00:38
   --- ------------------------------------ 3.4/38.5 MB 687.1 kB/s eta 0:00:52
   --- ------------------------------------ 3.7/38.5 MB 715.2 kB/s eta 0:00:49
   ---- ----------------------------------- 4.2/38.5 MB 765.0 kB/s eta 0:00:45
   ---- ----------------------------------- 4.5/38.5 MB 791.8 kB/s eta 0:00:44
   ---- ----------------------------------- 4.7/38.5 MB 814.9 kB/s eta 0:00:42
   ----- ---------------------------------- 5.2/38.5 MB 859.2 kB/s eta 0:00:39
   ----- ---------------------------------- 5.5/38.5 MB 880.7 kB/s eta 0:00:38
   ----- ---------------------------------- 5.5/38.5 MB 880.7 kB/s eta 0:00:38
   ------ --------------------------------- 6.0/38.5 MB 900.3 kB/s eta 0:00:37
   ------ --------------------------------- 6.3/38.5 MB 912.3 kB/s eta 0:00:36
   ------ --------------------------------- 6.6/38.5 MB 934.3 kB/s eta 0:00:35
   ------- -------------------------------- 6.8/38.5 MB 934.2 kB/s eta 0:00:34
   ------- -------------------------------- 7.1/38.5 MB 952.5 kB/s eta 0:00:33
   ------- -------------------------------- 7.1/38.5 MB 952.5 kB/s eta 0:00:33
   ------- -------------------------------- 7.1/38.5 MB 952.5 kB/s eta 0:00:33
   ------- -------------------------------- 7.3/38.5 MB 907.8 kB/s eta 0:00:35
   ------- -------------------------------- 7.6/38.5 MB 912.1 kB/s eta 0:00:34
   -------- ------------------------------- 7.9/38.5 MB 923.3 kB/s eta 0:00:34
   -------- ------------------------------- 8.4/38.5 MB 949.1 kB/s eta 0:00:32
   --------- ------------------------------ 8.9/38.5 MB 981.7 kB/s eta 0:00:31
   --------- ------------------------------ 9.2/38.5 MB 990.3 kB/s eta 0:00:30
   --------- ------------------------------ 9.2/38.5 MB 990.3 kB/s eta 0:00:30
   --------- ------------------------------ 9.2/38.5 MB 990.3 kB/s eta 0:00:30
   --------- ------------------------------ 9.2/38.5 MB 990.3 kB/s eta 0:00:30
   --------- ------------------------------ 9.2/38.5 MB 990.3 kB/s eta 0:00:30
   --------- ------------------------------ 9.2/38.5 MB 990.3 kB/s eta 0:00:30
   --------- ------------------------------ 9.2/38.5 MB 990.3 kB/s eta 0:00:30
   ---------- ----------------------------- 9.7/38.5 MB 898.8 kB/s eta 0:00:33
   ---------- ----------------------------- 10.0/38.5 MB 908.9 kB/s eta 0:00:32
   ---------- ----------------------------- 10.5/38.5 MB 936.1 kB/s eta 0:00:30
   ----------- ---------------------------- 10.7/38.5 MB 947.9 kB/s eta 0:00:30
   ----------- ---------------------------- 11.3/38.5 MB 970.6 kB/s eta 0:00:29
   ----------- ---------------------------- 11.5/38.5 MB 981.6 kB/s eta 0:00:28
   ------------ --------------------------- 12.1/38.5 MB 1.0 MB/s eta 0:00:27
   ------------- -------------------------- 12.6/38.5 MB 1.0 MB/s eta 0:00:26
   ------------- -------------------------- 12.8/38.5 MB 1.0 MB/s eta 0:00:25
   ------------- -------------------------- 13.1/38.5 MB 1.0 MB/s eta 0:00:25
   -------------- ------------------------- 13.6/38.5 MB 1.1 MB/s eta 0:00:24
   -------------- ------------------------- 13.9/38.5 MB 1.1 MB/s eta 0:00:24
   -------------- ------------------------- 14.2/38.5 MB 1.1 MB/s eta 0:00:23
   --------------- ------------------------ 14.7/38.5 MB 1.1 MB/s eta 0:00:22
   --------------- ------------------------ 14.7/38.5 MB 1.1 MB/s eta 0:00:22
   --------------- ------------------------ 14.7/38.5 MB 1.1 MB/s eta 0:00:22
   --------------- ------------------------ 14.7/38.5 MB 1.1 MB/s eta 0:00:22
   --------------- ------------------------ 14.7/38.5 MB 1.1 MB/s eta 0:00:22
   --------------- ------------------------ 14.7/38.5 MB 1.1 MB/s eta 0:00:22
   --------------- ------------------------ 14.9/38.5 MB 1.0 MB/s eta 0:00:24
   --------------- ------------------------ 15.2/38.5 MB 1.0 MB/s eta 0:00:23
   ---------------- ----------------------- 15.7/38.5 MB 1.0 MB/s eta 0:00:23
   ---------------- ----------------------- 16.0/38.5 MB 1.0 MB/s eta 0:00:22
   ---------------- ----------------------- 16.3/38.5 MB 1.0 MB/s eta 0:00:22
   ----------------- ---------------------- 16.8/38.5 MB 1.1 MB/s eta 0:00:21
   ----------------- ---------------------- 16.8/38.5 MB 1.1 MB/s eta 0:00:21
   ------------------ --------------------- 17.6/38.5 MB 1.1 MB/s eta 0:00:20
   ------------------ --------------------- 18.1/38.5 MB 1.1 MB/s eta 0:00:19
   ------------------- -------------------- 18.6/38.5 MB 1.1 MB/s eta 0:00:18
   ------------------- -------------------- 18.9/38.5 MB 1.1 MB/s eta 0:00:18
   ------------------- -------------------- 19.1/38.5 MB 1.1 MB/s eta 0:00:18
   -------------------- ------------------- 19.7/38.5 MB 1.1 MB/s eta 0:00:17
   -------------------- ------------------- 19.7/38.5 MB 1.1 MB/s eta 0:00:17
   -------------------- ------------------- 19.7/38.5 MB 1.1 MB/s eta 0:00:17
   -------------------- ------------------- 19.7/38.5 MB 1.1 MB/s eta 0:00:17
   -------------------- ------------------- 19.7/38.5 MB 1.1 MB/s eta 0:00:17
   -------------------- ------------------- 19.7/38.5 MB 1.1 MB/s eta 0:00:17
   -------------------- ------------------- 19.7/38.5 MB 1.1 MB/s eta 0:00:17
   -------------------- ------------------- 19.7/38.5 MB 1.1 MB/s eta 0:00:17
   -------------------- ------------------- 19.9/38.5 MB 1.0 MB/s eta 0:00:18
   -------------------- ------------------- 20.2/38.5 MB 1.0 MB/s eta 0:00:18
   --------------------- ------------------ 20.7/38.5 MB 1.1 MB/s eta 0:00:17
   --------------------- ------------------ 21.0/38.5 MB 1.1 MB/s eta 0:00:17
   ---------------------- ----------------- 21.5/38.5 MB 1.1 MB/s eta 0:00:16
   ---------------------- ----------------- 21.8/38.5 MB 1.1 MB/s eta 0:00:16
   ---------------------- ----------------- 22.0/38.5 MB 1.1 MB/s eta 0:00:16
   ----------------------- ---------------- 22.8/38.5 MB 1.1 MB/s eta 0:00:15
   ------------------------ --------------- 23.3/38.5 MB 1.1 MB/s eta 0:00:14
   ------------------------ --------------- 23.9/38.5 MB 1.1 MB/s eta 0:00:13
   ------------------------ --------------- 23.9/38.5 MB 1.1 MB/s eta 0:00:13
   ------------------------- -------------- 24.1/38.5 MB 1.1 MB/s eta 0:00:13
   ------------------------- -------------- 24.1/38.5 MB 1.1 MB/s eta 0:00:13
   ------------------------- -------------- 24.1/38.5 MB 1.1 MB/s eta 0:00:13
   ------------------------- -------------- 24.6/38.5 MB 1.1 MB/s eta 0:00:13
   ------------------------- -------------- 24.9/38.5 MB 1.1 MB/s eta 0:00:13
   -------------------------- ------------- 25.2/38.5 MB 1.1 MB/s eta 0:00:12
   -------------------------- ------------- 25.2/38.5 MB 1.1 MB/s eta 0:00:12
   -------------------------- ------------- 25.2/38.5 MB 1.1 MB/s eta 0:00:12
   -------------------------- ------------- 25.2/38.5 MB 1.1 MB/s eta 0:00:12
   -------------------------- ------------- 25.7/38.5 MB 1.1 MB/s eta 0:00:12
   -------------------------- ------------- 25.7/38.5 MB 1.1 MB/s eta 0:00:12
   -------------------------- ------------- 25.7/38.5 MB 1.1 MB/s eta 0:00:12
   -------------------------- ------------- 25.7/38.5 MB 1.1 MB/s eta 0:00:12
   -------------------------- ------------- 25.7/38.5 MB 1.1 MB/s eta 0:00:12
   -------------------------- ------------- 25.7/38.5 MB 1.1 MB/s eta 0:00:12
   -------------------------- ------------- 25.7/38.5 MB 1.1 MB/s eta 0:00:12
   -------------------------- ------------- 25.7/38.5 MB 1.1 MB/s eta 0:00:12
   -------------------------- ------------- 25.7/38.5 MB 1.1 MB/s eta 0:00:12
   -------------------------- ------------- 25.7/38.5 MB 1.1 MB/s eta 0:00:12
   -------------------------- ------------- 25.7/38.5 MB 1.1 MB/s eta 0:00:12
   -------------------------- ------------- 26.0/38.5 MB 1.0 MB/s eta 0:00:13
   --------------------------- ------------ 26.2/38.5 MB 1.0 MB/s eta 0:00:13
   --------------------------- ------------ 26.2/38.5 MB 1.0 MB/s eta 0:00:13
   --------------------------- ------------ 26.2/38.5 MB 1.0 MB/s eta 0:00:13
   --------------------------- ------------ 26.5/38.5 MB 1.0 MB/s eta 0:00:12
   --------------------------- ------------ 26.5/38.5 MB 1.0 MB/s eta 0:00:12
   --------------------------- ------------ 26.5/38.5 MB 1.0 MB/s eta 0:00:12
   --------------------------- ------------ 26.7/38.5 MB 984.0 kB/s eta 0:00:12
   --------------------------- ------------ 26.7/38.5 MB 984.0 kB/s eta 0:00:12
   --------------------------- ------------ 26.7/38.5 MB 984.0 kB/s eta 0:00:12
   --------------------------- ------------ 26.7/38.5 MB 984.0 kB/s eta 0:00:12
   ---------------------------- ----------- 27.0/38.5 MB 966.8 kB/s eta 0:00:12
   ---------------------------- ----------- 27.0/38.5 MB 966.8 kB/s eta 0:00:12
   ---------------------------- ----------- 27.0/38.5 MB 966.8 kB/s eta 0:00:12
   ---------------------------- ----------- 27.0/38.5 MB 966.8 kB/s eta 0:00:12
   ---------------------------- ----------- 27.0/38.5 MB 966.8 kB/s eta 0:00:12
   ---------------------------- ----------- 27.0/38.5 MB 966.8 kB/s eta 0:00:12
   ---------------------------- ----------- 27.3/38.5 MB 928.6 kB/s eta 0:00:13
   ---------------------------- ----------- 27.3/38.5 MB 928.6 kB/s eta 0:00:13
   ---------------------------- ----------- 27.3/38.5 MB 928.6 kB/s eta 0:00:13
   ---------------------------- ----------- 27.3/38.5 MB 928.6 kB/s eta 0:00:13
   ---------------------------- ----------- 27.3/38.5 MB 928.6 kB/s eta 0:00:13
   ---------------------------- ----------- 27.5/38.5 MB 900.5 kB/s eta 0:00:13
   ---------------------------- ----------- 27.5/38.5 MB 900.5 kB/s eta 0:00:13
   ---------------------------- ----------- 27.5/38.5 MB 900.5 kB/s eta 0:00:13
   ---------------------------- ----------- 27.8/38.5 MB 913.5 kB/s eta 0:00:12
   ----------------------------- ---------- 28.0/38.5 MB 913.6 kB/s eta 0:00:12
   ----------------------------- ---------- 28.3/38.5 MB 915.8 kB/s eta 0:00:12
   ----------------------------- ---------- 28.6/38.5 MB 917.4 kB/s eta 0:00:11
   ----------------------------- ---------- 28.6/38.5 MB 917.4 kB/s eta 0:00:11
   ------------------------------ --------- 29.1/38.5 MB 917.5 kB/s eta 0:00:11
   ------------------------------ --------- 29.1/38.5 MB 917.5 kB/s eta 0:00:11
   ------------------------------ --------- 29.4/38.5 MB 910.7 kB/s eta 0:00:11
   ------------------------------ --------- 29.6/38.5 MB 909.2 kB/s eta 0:00:10
   ------------------------------ --------- 29.6/38.5 MB 909.2 kB/s eta 0:00:10
   ------------------------------ --------- 29.6/38.5 MB 909.2 kB/s eta 0:00:10
   ------------------------------- -------- 29.9/38.5 MB 925.9 kB/s eta 0:00:10
   ------------------------------- -------- 29.9/38.5 MB 925.9 kB/s eta 0:00:10
   ------------------------------- -------- 29.9/38.5 MB 925.9 kB/s eta 0:00:10
   ------------------------------- -------- 30.1/38.5 MB 916.6 kB/s eta 0:00:10
   ------------------------------- -------- 30.4/38.5 MB 917.2 kB/s eta 0:00:09
   ------------------------------- -------- 30.4/38.5 MB 917.2 kB/s eta 0:00:09
   -------------------------------- ------- 30.9/38.5 MB 922.3 kB/s eta 0:00:09
   -------------------------------- ------- 31.2/38.5 MB 926.2 kB/s eta 0:00:08
   -------------------------------- ------- 31.7/38.5 MB 927.2 kB/s eta 0:00:08
   --------------------------------- ------ 32.0/38.5 MB 928.7 kB/s eta 0:00:08
   --------------------------------- ------ 32.2/38.5 MB 928.2 kB/s eta 0:00:07
   --------------------------------- ------ 32.5/38.5 MB 927.7 kB/s eta 0:00:07
   ---------------------------------- ----- 33.0/38.5 MB 929.2 kB/s eta 0:00:06
   ---------------------------------- ----- 33.3/38.5 MB 929.2 kB/s eta 0:00:06
   ----------------------------------- ---- 33.8/38.5 MB 937.9 kB/s eta 0:00:06
   ----------------------------------- ---- 34.1/38.5 MB 937.9 kB/s eta 0:00:05
   ----------------------------------- ---- 34.3/38.5 MB 935.4 kB/s eta 0:00:05
   ----------------------------------- ---- 34.3/38.5 MB 935.4 kB/s eta 0:00:05
   ----------------------------------- ---- 34.6/38.5 MB 929.6 kB/s eta 0:00:05
   ------------------------------------ --- 34.9/38.5 MB 926.7 kB/s eta 0:00:04
   ------------------------------------ --- 35.1/38.5 MB 941.9 kB/s eta 0:00:04
   ------------------------------------- -- 35.7/38.5 MB 949.2 kB/s eta 0:00:04
   ------------------------------------- -- 35.9/38.5 MB 953.0 kB/s eta 0:00:03
   ------------------------------------- -- 36.2/38.5 MB 956.0 kB/s eta 0:00:03
   -------------------------------------- - 36.7/38.5 MB 956.4 kB/s eta 0:00:02
   -------------------------------------- - 37.0/38.5 MB 955.9 kB/s eta 0:00:02
   -------------------------------------- - 37.2/38.5 MB 954.0 kB/s eta 0:00:02
   ---------------------------------------  37.7/38.5 MB 956.0 kB/s eta 0:00:01

In [142]:
from sklearn.metrics.pairwise import cosine_similarity

In [143]:
similarity_score = cosine_similarity(pt)

In [144]:
similarity_score.shape

(706, 706)

In [159]:
def recommend(book_name):
    index = np.where(pt.index==book_name)[0][0]
    similar_item = sorted(list(enumerate(similarity_score[index])),key=lambda x:x[1],reverse=True)[1:6]
    for i in similar_item: 
        print(pt.index[i[0]])

In [161]:
recommend('Brave New World')

1984
How to Be Good
Naked
Five Quarters of the Orange
Love in the Time of Cholera (Penguin Great Books of the 20th Century)

In [151]:
np.where(pt.index=='1984')[0][0]

np.int64(0)

In [156]:
sorted(list(enumerate(similarity_score[0])),key=lambda x:x[1],reverse=True)[1:6]

[(47, np.float64(0.2702651417103732)),
 (545, np.float64(0.2639619371123497)),
 (82, np.float64(0.23669374347400993)),
 (634, np.float64(0.23299389358170394)),
 (551, np.float64(0.2262639743141286))]